site_name: StrucEng Library
site_url: https://strucenglib.ethz.ch
site_description: >-
  StrucEng Library

repo_name: kfmResearch-NumericsTeam/Struc_Eng_Library_Website
repo_url: https://github.com/kfmResearch-NumericsTeam/Struc_Eng_Library_Website

extra_javascript:
  - assets/website/code.js
extra_css:
  - assets/website/style.css

plugins:
  - search
  # https://github.com/byrnereese/mkdocs-minify-plugin
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
      css_files:
        - assets/website/style.css

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: blue grey
      accent: red
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/website/favicon.png
  logo: assets/website/se.png


copyright: Copyright &copy; 2022 and later, The StrucEng Library Authors

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kfmResearch-NumericsTeam/Struc_Eng_Library_Website
      name: StrucEng Library on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
      name: StrucEng Library on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/
      name: StrucEng Library on LinkedIn


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Website navigation:
nav:
  - Home: index.md
  - 'See in Action': action.md
  - 'Rhino 3D Plugin':
      - Home: strucenglib_plugin/home.md
      - Screenshots: strucenglib_plugin/screenshots.md
      - Installation:
          - Prerequisites: strucenglib_plugin/getting_started.md
          - Installation: strucenglib_plugin/installation.md
      - Usage Guide:
          - 'GUI Workflow': strucenglib_plugin/usage/guide.md
          - 'Troubleshooting':   strucenglib_plugin/usage/troubleshooting.md
      - Developer:
          Documentation: strucenglib_plugin/developer/developer.md
          Changelog: https://github.com/kfmResearch-NumericsTeam/StrucEng_Library_Plug_in/blob/master/CHANGELOG
          Source Code: https://github.com/kfmResearch-NumericsTeam/StrucEng_Library_Plug_in
  - 'Other Component':
      - other_component/home.md
  - About: about.md
