site_name: ''
site_url: https://strucenglib.ethz.ch
site_description: >-
  StrucEng Library

repo_name: StrucEng-Library-kfmresearch/strucenglib-website
repo_url: https://github.com/StrucEng-Library-kfmresearch/strucenglib-website
 
extra_javascript:
  - assets/website/code.js
extra_css:
  - assets/website/style.css

plugins:
  - search
  # https://github.com/byrnereese/mkdocs-minify-plugin
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
      css_files:
        - assets/website/style.css

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: blue grey
      accent: red
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/website/favicon.png
  logo: assets/website/logo-web-5.svg
  logo_drawer: assets/website/logo-web-0.svg


copyright: Copyright &copy; 2022 and later, The StrucEng Library Authors

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/StrucEng-Library-kfmresearch
      name: StrucEng Library on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
      name: StrucEng Library on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/
      name: StrucEng Library on LinkedIn


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Website navigation:
nav:
  - Home: index.md
  - 'See in Action': action.md
  - 'Rhinoceros 3D Plugin':
      - Home: strucenglib_plugin/home.md
      - Installation:
          - Prerequisites: strucenglib_plugin/prerequisites.md
          - Install for Abaqus: strucenglib_plugin/install_for_abaqus.md
          - Install for Ansys: strucenglib_plugin/install_for_ansys.md
      - Usage Guide:
          - 'StrucEngLib Server': strucenglib_plugin/server.md
          - 'Troubleshooting':   strucenglib_plugin/usage/troubleshooting.md
      - Developer:
          Documentation: strucenglib_plugin/developer/developer.md
          Changelog: https://github.com/StrucEng-Library-kfmresearch/strucenglib-rhino3d-plugin/blob/master/CHANGELOG
          Source Code: https://github.com/StrucEng-Library-kfmresearch/strucenglib-rhino3d-plugin
  - 'StrucEng Library Snippets':
      - Basics: 
          -  Workflow: strucenglib_snippets/basics/workflow.md        
          -  Importing moduls and classes: strucenglib_snippets/basics/imports.md
      - Structure: 
          -  Structure object: strucenglib_snippets/Structure/object.md  
          -  Summary: strucenglib_snippets/Structure/summary.md  
          -  Load and save: strucenglib_snippets/Structure/load_and_save.md  
      - Elements:
          -  Basic functionalities: strucenglib_snippets/elements /basics.md  
          -  Beam elements: strucenglib_snippets/elements/beam.md  
          -  Shell elements: strucenglib_snippets/ elements /shell.md  
          -  MPC elements: strucenglib_snippets/Structure/mpc.md  
  - 'Compas FEA':
      - Home: compas_fea/home.md
      - General: compas_fea/general.md
      - Adjustments: compas_fea/adjustments.md
      
  - About: about.md
