site_name: ''
site_url: https://strucenglib.ethz.ch
site_description: >-
  StrucEng Library

repo_name: StrucEng-Library-kfmresearch/strucenglib-website
repo_url: https://github.com/StrucEng-Library-kfmresearch/strucenglib-website
 
extra_javascript:
  - assets/website/code.js
extra_css:
  - assets/website/style.css

plugins:
  - search
  # https://github.com/byrnereese/mkdocs-minify-plugin
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
      css_files:
        - assets/website/style.css

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: blue grey
      accent: red
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/website/favicon.png
  logo: assets/website/logo-web-5.svg
  logo_drawer: assets/website/logo-web-0.svg


copyright: Copyright &copy; 2022 and later, The StrucEng Library Authors

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/StrucEng-Library-kfmresearch
      name: StrucEng Library on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
      name: StrucEng Library on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/
      name: StrucEng Library on LinkedIn


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Website navigation:
nav:
  - Home: index.md
  - 'See in Action': action.md
  - 'Rhinoceros 3D Plugin':
      - Home: strucenglib_plugin/home.md
      - Installation:
          - Prerequisites: strucenglib_plugin/prerequisites.md
          - Install for Abaqus: strucenglib_plugin/install_for_abaqus.md
          - Install for Ansys: strucenglib_plugin/install_for_ansys.md
      - Usage Guide:
          - 'StrucEngLib Server': strucenglib_plugin/server.md
          - 'Troubleshooting':   strucenglib_plugin/usage/troubleshooting.md
      - Developer:
          Documentation: strucenglib_plugin/developer/developer.md
          Python Developer Mode: strucenglib_plugin/developer/python_developer_mode.md
          Changelog: https://github.com/StrucEng-Library-kfmresearch/strucenglib-rhino3d-plugin/blob/master/CHANGELOG.md
          Source Code: https://github.com/StrucEng-Library-kfmresearch/strucenglib-rhino3d-plugin
  - 'StrucEng Library Snippets':
      - Home: strucenglib_snippets/home.md  
      - Basics:
          - Overview: strucenglib_snippets/basics/overview.md      
          - Workflow: strucenglib_snippets/basics/workflow.md     
      - Actions on structures: 
          #- Load generators: strucenglib_snippets/actions/general_generators.md     
          - Self-Weight: strucenglib_snippets/actions/self_weight.md
          - General actions: strucenglib_snippets/actions/general.md  
          - Imposed loads on buildings: strucenglib_snippets/actions/buildings.md                      
          #- Traffic loads on bridges: strucenglib_snippets/actions/traffic_loads.md  
          - Seismic actions: strucenglib_snippets/actions/seismic.md
          - Actions on structures exposed to fire: strucenglib_snippets/actions/fire.md   
      - Concrete structures: 
          - Material models: strucenglib_snippets/concrete_structures/material_models.md     
          - Code checks: strucenglib_snippets/actions/concrete_structures/code_checks.md          
      - Masonry structures: 
          - Material models: strucenglib_snippets/masonry_structures/material_models.md     
          - Code checks: strucenglib_snippets/actions/masonry_structures/code_checks.md     
      - Safety concepts: 
          - PSF: strucenglib_snippets/saftey_concepts/psf.md
          - ECOV: strucenglib_snippets/saftey_concepts/ecov.md
      - Grafical outputs:
          - Prepost plots: strucenglib_snippets/grafical_outputs/prepost_plots.md    
          - Numerical results: strucenglib_snippets/grafical_outputs/numerical_results.md    
      - Examples:
          - Example 1: strucenglib_snippets/examples/all_functionalities.md
          
          
  - 'Patches for Compas FEA':
      - Home: compas_fea/home.md 
      - Basics: compas_fea/basics.md   
      - Structure: compas_fea/structure.md   
      - Elements: compas_fea/nodes.md
      - Sets: compas_fea/elements.md
      - Materials: compas_fea/sets.md
      - Sections: compas_fea/sections.md
      - Properties: compas_fea/materials.md
      - Constraints: compas_fea/properties.md
      - Loads:  compas_fea/loads.md             
      - Steps:  compas_fea/displacements.md             
      - Analyses: compas_fea/steps.md             
      - Results: compas_fea/analysis.md                         
      - Developer Notes: compas_fea/dev_notes.md        
  - About: about.md
