site_name: The StrucEng Library Project
site_url: https://kfmresearch-numericsteam.github.io/Struc_Eng_Library_Website
site_description: >-
  StrucEng Library

repo_name: kfmResearch-NumericsTeam/Struc_Eng_Library_Website
repo_url: https://github.com/kfmResearch-NumericsTeam/Struc_Eng_Library_Website


theme:
  name: material
  custom_dir: overrides
  # features:
  #   - navigation.tabs
  #   - navigation.tabs.sticky

  language: en
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: blue grey
      accent: red

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/se.png



extra_javascript:
  - assets/code.js
extra_css:
  - assets/style.css

copyright: Copyright &copy; 2022 and later, The StrucEng Library Authors

extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - 'See in Action': action.md
  - 'Rhino 3D Plugin':
      - Home: strucenglib_plugin/home.md
      - Screenshots: strucenglib_plugin/screenshots.md
      - Installation:
          - Prerequisites: strucenglib_plugin/getting_started.md
          - Installation: strucenglib_plugin/installation.md
      - Usage Guide:
          - 'GUI Workflow': strucenglib_plugin/usage/guide.md
          - 'Troubleshooting':   strucenglib_plugin/usage/troubleshooting.md
      - Developer:
          Documentation:
          - Design Decisions: strucenglib_plugin/developer/developer.md
          - Building the Plugin: strucenglib_plugin/developer/developer.md
          - Releasing a new Version: strucenglib_plugin/developer/developer.md
          Changelog: https://github.com/kfmResearch-NumericsTeam/StrucEng_Library_Plug_in/blob/master/CHANGELOG
          Source Code: https://github.com/kfmResearch-NumericsTeam/StrucEng_Library_Plug_in
  - 'Other Component':
      - other_component/home.md
  - About: about.md
