site_name: StrucEng Library
site_url: https://strucenglib.ch


theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky





extra_javascript:
  - assets/code.js
extra_css:
  - assets/style.css

copyright: Copyright &copy; 2022, The StrucEng Library Authors

extra:
  generator: false

nav:
  - Home: home.md
  - Features: tutorial.md
  - Get Started: get_started.md
  - Documentation: documentation.md
  - About: about.md
