site_name: StrucEng Library
site_url: https://strucenglib.ch
site_description: >-
  The StrucEng Library Project Site

repo_name: kfmResearch-NumericsTeam/Struc_Eng_Library_Website
repo_url: https://github.com/kfmResearch-NumericsTeam/Struc_Eng_Library_Website


theme:
  name: material
  custom_dir: overrides
  # features:
  #   - navigation.tabs
  #   - navigation.tabs.sticky

  language: en
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: blue grey
      accent: red

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo





extra_javascript:
  - assets/code.js
extra_css:
  - assets/style.css

copyright: Copyright &copy; 2022, The StrucEng Library Authors

extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Features: tutorial.md
  - Getting Started:
      - Prerequisites: install/getting_started.md
      - Installation: install/installation.md
  - Tutorials: usage_guide.md
  - Documentation:
      - Mechanical Models: documentation.md
      - Rhinoceros 3D Plugin: documentation.md
  - About: about.md
