name: Build Website
on:
  push:
    branches:
    - master
  
  workflow_dispatch:

permissions:
   contents: write
   
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
    

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          CUSTOM_DOMAIN: strucenglib.ethz.ch
          REQUIREMENTS: .github/requirements.txt
          
      - name: fix-permissions
        run: |   
         sudo chmod 777 -R ./site
         
      - name: add-compas-doc
        run: |
          git clone https://github.com/StrucEng-Library-kfmresearch/strucenglib-website.git compas
          cd compas
          git checkout docs/compas
          ls -al
          cd ../
          mkdir -p site/docs
          cp -rf compas/docs/* site/docs/
          ls -al site/docs

      - name: add-compas_fea-doc
        run: |
          git clone https://github.com/StrucEng-Library-kfmresearch/strucenglib-website.git compas_fea
          cd compas_fea
          git switch docs/compas_fea
          ls -al
          cd ../
          mkdir -p site/docs
          cp -rf compas_fea/docs/* site/docs/
          ls -al site/docs

      - name: deploy-mkdocs-with-compas-doc
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `master` in `refs/heads/master`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
